### ISSUE TITLE
How can I implement douban dataset?

### ISSUE THREAD

**Issue by jindeok** [vinhsuhi/GAlign#1]
Thanks for sharing your codes! though I have one question..
When I replace string allmv-tmdb into douban online/offine

e.g.
python -u network_alignment.py --source_dataset graph_data/douban/online/graphsage --target_dataset graph_data/douban/offline/graphsage --groundtruth graph_data/douban/dictionaries/groundtruth GAlign --log --GAlign_epochs 10 --refinement_epochs 50 --cuda

It leads to the error:
![image](https://user-images.githubusercontent.com/35905280/105635715-bc803400-5ea7-11eb-8e24-32c2c87b826f.png)

while allmv-tmdb doesnt shows any error..
can you give me some tips on this???

Thanks for the reading .

**Comment by vinhsuhi** [comment]
Thank you for your feedback, and sorry for my late response. 
This problem happened because the data we've updated missed some files which were ignored by gitignore. 
We've already updated the data and solve this problem.
